### ISSUE TITLE
pipeline stuck at 'Building DAG of jobs'

### ISSUE THREAD

**Issue by ndussex** [NBISweden/GenErode#47]
Hi, 

After modifying a rule (common.smk) to run GERP scores and to split the genomes in more chunks so that the step run more quickly, the pipeline (dry or main run) gets stuck to 

'Config file config/config.yaml is extended by additional config specified via the command line.
Building DAG of jobs...'

The only job that is run is the job splitting the genomes into chunk*.bed files and this is done as modified in my rule (i.e. divide the genome into 2000 instead of 200 chunks). The first time I did this, I had to cancel the run,  delete the 'my_Ref_path/gerp' directtory and restart it as I noticed that those bed files were still in the original set up (i.e. 200 chunks). But other than that, the pipeline was running as it was supposed to. But now, the run gets stuck as above. 

So, I the did the following to try and fix it: 

- deleted all logs relevant to the GERP rule
- deleted again the my_Ref_path/gerp
- cleaned my conda environment
- started a new tmux session
- checked if my other instances of the pipeline worked (they do).

The only file that I edited was common.smk, so I am not sure what else could have gone wrong. Is there any other file/logs I should delete or something else I could check to try and fix this?

Thanks a lot!
Nic

**Comment by verku** [comment]
Hi!

I realised that you'd have to modify more files and that this will unfortunately trigger a re-run of the pipeline:

GERP is taking the repeat-masked per-sample BCF files as input, it does not use the merged VCF/BCF file. This would be fine, but you will also need to remove the unplaced scaffolds from the reference genome fasta file. Even if you keep the same file name, the time stamp would be updated which will cause Snakemake to re-run everything based on the reference genome fasta file.

So if you decide to remove the unplaced scaffolds, I'd suggest to re-run the pipeline from the start with only the GERP step set to "True". If you decide to do that in the same directory as your previous pipeline runs, you'd have to rename the reference genome fasta file without the unplaced scaffolds, so that GenErode does not overwrite your results based on the full reference genome fasta file.

**Comment by verku** [comment]
I'm glad to hear that you found a solution, fingers crossed for your remaining analyses!
